# Generated by Django 2.0.6 on 2018-06-08 07:01

import PyLightORM.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(default='', max_length=255, verbose_name='Name of the pi client')),
                ('serverAddress', models.CharField(default='', max_length=255, verbose_name='Address of the server that set the ip of the pi')),
            ],
        ),
        migrations.CreateModel(
            name='IOs',
            fields=[
                ('ioNr', models.IntegerField(primary_key=True, serialize=False, verbose_name='physical io nr on pi')),
            ],
        ),
        migrations.CreateModel(
            name='IOTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioType', models.CharField(choices=[(PyLightORM.models.IOType('IOType.NONE'), 'IOType.NONE'), (PyLightORM.models.IOType('IOType.OUTPUT'), 'IOType.OUTPUT'), (PyLightORM.models.IOType('IOType.INPUT'), 'IOType.INPUT')], max_length=255, verbose_name='Type of output')),
            ],
        ),
        migrations.CreateModel(
            name='UsedIOs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='human readable name for the io')),
                ('active', models.BooleanField(default=False, verbose_name='Active/Non Active IO')),
                ('pin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PyLightORM.IOs', verbose_name='Pin nr')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PyLightORM.IOTypes', verbose_name='Type of IO')),
            ],
        ),
    ]
