# Generated by Django 2.0.6 on 2018-06-08 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyLightORM', '0002_load_fixtures_used_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ios',
            name='usedIOId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PyLightORM.UsedIOs', verbose_name='link to the used ios'),
        ),
    ]
