# Generated by Django 2.0.6 on 2018-06-08 03:44

from django.db import migrations
from django.core.management import call_command

def load_ios(apps, schema_editor):
    call_command("loaddata", "io_fixtures.json")

class Migration(migrations.Migration):

    dependencies = [
        ('PyLightORM', '0003_changeUsedIOs_ManyToOne'),
    ]

    operations = [
        migrations.RunPython(load_ios),
    ]
